version: '3'
services:
  next-js-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: enjoylife-pj01-frontend
    volumes:
      - ./src/app:/app
    command: sh -c "npm run dev"
    tty: true
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - next-js-app
